version: '3.9'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - 1883
      - 9001
    volumes:
      - ./config:/mosquitto/config
      - ./config:/mosquitto/data
  #   networks:
  #     broker2db_net:
  #       ipv4_address: 10.5.0.5
  # broker2db:
  #   container_name: broker2db
  #   image: broker2db
  #   depends_on:
  #     - mosquitto

volumes:
  config:
  data:

# networks:
#   broker2db_net:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.5.0.0/16
#           gateway: 10.5.0.1