version: '3.9'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - 1883
      - 9001
    volumes:
      - ./config:/mosquitto/config
      - ./config:/mosquitto/data
volumes:
  config:
  data:
