version: '3.9'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    ports:
      - 1883
      - 9001
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - ./config/mosquitto:/mosquitto/data
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    env_file:
      - ./config/influxdb/influxdb.env
    ports:
      - "8086:8086"
  mqtt_influxdb_bridge:
    container_name: mqtt_influxdb_bridge
    image: mqtt_influxdb_bridge
    volumes:
      - ./config/influxdb/influxdb.env:/app/influxdb.env
      - ../devices.csv:/app/devices.csv
      - ./.env:/app/.env
    depends_on:
      - mosquitto
      - influxdb
  controller:
    container_name: controller
    image: controller
    volumes:
      - ./config/influxdb/influxdb.env:/app/influxdb.env
      - ../devices.csv:/app/devices.csv
      - ../map.csv:/app/map.csv
      - ./.env:/app/.env
    depends_on:
      - mosquitto
      - influxdb




volumes:
  config: {}
  data: {}
  influxdb: {}